### ISSUE TITLE
跟我一起入DSL坑吧

### ISSUE THREAD

**Issue by ice1000** [ice1000/Ixe#1]
@Predator-SD 呐

**Comment by Predator-SD** [comment]
ok,我看看

**Comment by Predator-SD** [comment]
@ice1000 mpl和mps什么鬼语言？

**Comment by Predator-SD** [comment]
用什么ide? @ice1000

**Comment by ice1000** [comment]
@Predator-SD 额，我在README里面有说的 :joy: 。这玩意极其强大，回去我给你看代码截图。<br/>
看README啊看README @Predator-SD :+1: <br/>
编辑器是[JetBrains的MPS](https://www.jetbrains.com/mps/?fromMenu)

**Comment by ice1000** [comment]
我更新了下README，看看这下说清楚没有，顺便检查下英文版的语法错误 @Predator-SD :joy:

**Comment by ice1000** [comment]
mps和mpl都不是语言，都只是保存AST的XML而已  :kissing:

**Comment by ice1000** [comment]
顺便推荐你一个IDE，写JavaScript的：[WebStorm](https://www.jetbrains.com/webstorm) 此乃真·神器

**Comment by ice1000** [comment]
@Predator-SD 跟我一起入坑吧 我把官方教程投在B站了 :anguished:

**Comment by lfkdsk** [comment]
(ΘˍΘ=)

**Comment by ice1000** [comment]
@lfkdsk 干嘛 你也要入MPS? 这个很好玩的 :joy:

**Comment by ice1000** [comment]
@lfkdsk 我今天试了试JustWe,感觉还不错，虽然AS gradle导入失败，但是我直接修改你的Demo的源码就能解决这个问题，刚刚学到逐帧动画那里。。
放学别跑，我还有一篮子问题要问你 :joy:

**Comment by ice1000** [comment]
@lfkdsk 我在学校，由于住校，手上的设备没USB，AS的真机调试貌似不支持OTG，所以调试很困难。。。
我回家了给你issue吧 :joy:
